config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#home'

  get 'rooms', to: 'pages#rooms'
  get 'activity', to: 'pages#activity'
  get 'dining', to: 'pages#dining'
  get 'contact', to: 'pages#contact'

  #get 'admin', to: 'pages#admin' #subject to change

  # Admin Management
  namespace :admin do
    root 'pages#home'
    resources :bookings, :payment_methods, :price_categories, :room_types, :rooms, :seasonal_rates, :view_types
    get 'daily_report', to: 'pages#daily_report'
    get 'price_selection', to: 'pages#price_selection'
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
    has_many :bookings
    has_many :rooms, through: :bookings
end

app/models/booking.rb
class Booking < ApplicationRecord
    # Should have a composite primary key here but it's more complex to do so with rails
    # I'll simply leave the table with the standard id as the primary key and add bill_id 
    # and room_id as foreign keys using has_many :through association
    belongs_to :bill
    belongs_to :room
    
end

app/models/guest.rb
class Guest < ApplicationRecord
    has_many :bills
end

app/models/neighborhood.rb
class Neighborhood < ApplicationRecord
    has_many :rooms
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
    has_many :bills
end

app/models/price_category.rb
class PriceCategory < ApplicationRecord
    belongs_to :season
    belongs_to :room_type
    belongs_to :view_type
    has_many :rooms
end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :price_category
    belongs_to :neighborhood

    has_many :bookings
    has_many :bills, through: :bookings
end

app/models/room_type.rb
class RoomType < ApplicationRecord
    has_many :price_categories
end

app/models/season.rb
class SeasonalRate < ApplicationRecord
    has_many :prices_categories
end

app/models/view_type.rb
class ViewType < ApplicationRecord
    has_many :price_categories
end

app/controllers/admin/bookings_controller.rb
class Admin::BookingsController < ApplicationController
        
    def index
    end
    
    def show
    end
    
    def new
    end
    
    def create
    end
    
    def update
    end   

    def destroy
    end

end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < ApplicationController

	def home
	end

	def daily_report
	end

	def price_selection
	end
		
end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < ApplicationController
		
	def index
	end

	def show
	end

	def new
	end

	def create
	end

	def update
	end

	def destroy
	end
	
end

app/controllers/admin/seasons_controller.rb
class Admin::SeasonsController < ApplicationController
		
	def index
	end

	def show
	end

	def new
	end

	def create
	end

	def update
	end

	def destroy
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
    end

    def rooms
	end

	def activity
	end
		
	def dining
	end
	
	def contact
	end
		
    

end

app/helpers/admin/view_type_helper.rb
module Admin::ViewTypeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/pages/daily_report.haml
%h2#admin-h2 Panneau administrateur
%h3.admin-h3 Rapport journalier

app/views/admin/pages/home.html.haml
%h2#admin-h2 Panneau administrateur
%h3.admin-h3 Principal
.row
    .col-md-3
        = link_to "Chambres", admin_rooms_path, :class => "btn btn-primary btn-admin-custom", :type => "button"
    .col-md-3
        = link_to "Prix", admin_price_selection_path, :class => "btn btn-primary btn-admin-custom", :type => "button"
    .col-md-3
        = link_to "Réservations", admin_bookings_path, :class => "btn btn-primary btn-admin-custom", :type => "button"
    .col-md-3
        = link_to "Rapport journalier", admin_daily_report_path, :class => "btn btn-primary btn-admin-custom", :type => "button"
%h3.admin-h3 Secondaire
.row
    .col-md-3
        = link_to "Types de chambre", admin_room_types_path, :class => "btn btn-secondary btn-admin-custom", :type => "button"
    .col-md-3
        = link_to "Méthodes de paiement", admin_payment_methods_path, :class => "btn btn-secondary btn-admin-custom", :type => "button"
    .col-md-3
        = link_to "Types de vue", admin_view_types_path, :class => "btn btn-secondary btn-admin-custom", :type => "button"

app/views/admin/pages/price_selection.html.haml
%h2#admin-h2 Panneau administrateur
%h3.admin-h3 Prix
%p.text-center Voulez-vous consulter les prix saisonniers ou les catégories de prix?
.row
    .col-md-3
    .col-md-3
        = link_to "Prix saisonnier", admin_seasonal_rates_path, :class => "btn btn-primary btn-admin-custom", :type => "button"
    .col-md-3
        = link_to "Catégories de prix", admin_price_categories_path, :class => "btn btn-primary btn-admin-custom", :type => "button"
    .col-md-3

app/views/layouts/_footer.html.haml
%footer.dk-footer
    .copyright
        .container-lg
            .row
                .col
                    %span Nagano Inn © 2021. Tous droits réservés
                .col
                    .copyright-menu
                        %ul
                            %li
                                = link_to "CHAMBRES & SUITES", "/rooms" 
                            %li
                                = link_to "ACTIVITÉS", "/activity" 
                            %li
                                = link_to "RESTAURATION", "/dining" 
                            %li
                                = link_to "CONTACTEZ-NOUS", "contact" 

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
    .container-lg
        - if !params[:controller].include?('admin/')
            = link_to image_tag( "logo_long.png"), "/", :class => "navbar-brand" 
            %button{:class => "navbar-toggler", :type => "button", :type => "button", :data-bs-toggle => "collapse", :data-bs-target => "#navbarSupportedContent", :aria-controls => "navbarSupportedContent", :aria-expanded => "false", :aria-label => "Toggle navigation"}
                %span.navbar-toggler-icon
            .collapse.navbar-collapse#navbarSupportedContent
            %ul.navbar-nav.me-auto.mb-2.mb-lg-0
                %li.nav-item
                    = link_to "CHAMBRES & SUITES", "/rooms", :class => "nav-link"
                %li.nav-item
                    = link_to "ACTIVITÉS", "/activity", :class => "nav-link" 
                %li.nav-item
                    = link_to "RESTAURATION", "/dining", :class => "nav-link" 
                %li.nav-item
                    = link_to "CONTACTEZ-NOUS", "/contact", :class => "nav-link"
            .btn-reserver
                %a{:class => "nav-link", :href => "#"} RÉSERVER
        - else 
            = link_to image_tag( "logo_long_admin.png"), "/admin", :class => "navbar-brand"
            = link_to "Retourner sur le site", root_path, :class => "btn btn-secondary nav-link", :type => "button"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nagano Inn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- FAVICON -->
    <%= favicon_link_tag asset_path('favicon.png') %>



  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container-lg">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/activity.html.haml
ACTIVITE

app/views/pages/contact.html.haml
CONTACT

app/views/pages/dining.html.haml
DINING

app/views/pages/home.html.haml
#home-img
    #home-msg
        Bienvenue sur le site de Nagano Inn, l'hôtel de vos désirs. Chez Nagano Inn, votre confort est notre priorité. En passant votre séjour chez nous, vous dites adieu aux problèmes et bonjour à la tranquillité d'esprit. 
        %br
        %br
        %strong Profitez d'un rabais de 25% pour la période du 8 février au 5 mars.

app/views/pages/rooms.html.haml
ROOMS